### ISSUE TITLE
播放地址参数错了

### ISSUE THREAD

**Issue by leidi0129** [Mamakou/DLNA_UPNP-Manager#2]
`///设置资源播放路径
- (void)setAVTransportURIStr:(NSString *)uriStr result:(YMUpnpResultBlock)result
{
    if(self.device == nil)return;
    YMUpnpAction *action = [[YMUpnpAction alloc]initWithAction:@"SetAVTransportURI"];
    [action setParamsElement:@"0" name:@"InstanceID"];
    [action setParamsElement:uriStr name:@"CurrentURI"];
    [action setParamsElement:@"" name:@"NextURIMetaData"];   //应该是 CurrentURIMetaData
    [self postRequestWithAction:action result:result];
}`

**Comment by Mamakou** [comment]
应该是代码copy的时候忘记改了。。。
